root=.
tmp_path=/tmp
build_name=app
build_log=build.log
valid_exts=.go,.tpl,.tmpl,.html
valid_paths=./
cmd=app
build_delay=600
colors=true
log_color_main=32
log_color_build=34
log_color_runner=36
build_args=
runner_args=
env_vars=